### ISSUE TITLE
Assertion error message for containsOnLeft doesn't contain actual left value

### ISSUE THREAD

**Issue by sesamzoo** [assertj/assertj-vavr#122]
# Description
#50 hasn't completely fixed assertion error messages on `Either`, because of this line in assertj-core's [`StandardRepresentation`](https://github.com/assertj/assertj-core/blob/3f654ef0d30225e3d820967f478c5582fba82121/src/main/java/org/assertj/core/presentation/StandardRepresentation.java#L218):
```java
    if (object instanceof Iterable<?>) return smartFormat((Iterable<?>) object);
```
This might affect other assertion error messages, too.

# Example
```java
assertThat(Either.left("hello")).containsOnLeft("hello world");
```
## Expected Behavior
leads to an assertion error message containing the actual value, f.i. like

> Expecting:
>  <"Left(hello)">
> to contain:
>  <"hello world"> on the [LEFT]
> but did not.

## Actual Behavior
leads to assertion error message

> Expecting:
>  <[]>
> to contain:
>  <"hello world">
> but did not.

# Tested with
- assertj-vavr 0.2.0

**Comment by mchmielarz** [comment]
Good catch. I'll fix it

**Comment by sesamzoo** [comment]
With upgrading to latest [assertj-core release 3.18.0](https://assertj.github.io/doc/#assertj-core-3-18-0-release-notes) this issue will be gone, because its `StandardRepresentation` does
> Honor toString if overridden in Iterable that are not collections.

**Comment by mchmielarz** [comment]
That's true. It wasn't fixed in the project because of custom error message factories. I'll update them and will be fiine
