### ISSUE TITLE
VavrAssumptions public methods return package-private types

### ISSUE THREAD

**Issue by kennymacleod** [assertj/assertj-vavr#141]
The various `assumeThat` methods in the `VavrAssumptions` class return package-private types rather than the public types returned by `VavrAssertions`.

For example, whereas `VavrAssertions#assertThat(Map)` returns a public `MapAssert` type, `VavrAssumptions#assumeThat(Map)` returns a package-private `AbstractMapAssert` type.

As a result, none of the `assumeThat` methods are usable from code outside of that package, since they won't even compile.

**Comment by mchmielarz** [comment]
Good point @kennymacleod! Will fix it!
