### ISSUE TITLE
TryAssert.contains should accept null as an expected value

### ISSUE THREAD

**Issue by jiffle** [assertj/assertj-vavr#29]
AbstractTryAssert.contains explicitly checks that the expectedValue is not equal to null.

There is no reason, however that the success case cannot be null (indeed if the Try is parameterised on Void it would be the only possible success response).

**Comment by pivovarit** [comment]
Good point, @jiffle - we'll take a look and fix

**Comment by pivovarit** [comment]
Will be released in the next release.
