### ISSUE TITLE
Add support for asserting left and right side of Either

### ISSUE THREAD

**Issue by jlorenzen** [assertj/assertj-vavr#69]
What are your thoughts on adding a `hasValueSatisfying` and `hasLeftValueSatisfying` methods to the `EitherAssert` class that is similar to [AbstractOptionalAssert](
http://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AbstractOptionalAssert.html#hasValueSatisfying-java.util.function.Consumer-)? Then one would be able to do the following:
```java
Either<Throwable, Person> result = createPerson();
assertThat(result).hasValueSatisfying(person -> {
    assertThat(person.getFirstName()).isEqualsTo("John");
});
```
and
```java
Either<Throwable, Person> result = createPerson();
assertThat(result).hasLeftValueSatisfying(throwable -> {
    assertThat(throwable.getMessage()).isEqualsTo("error");
});
```

If this is something everyone would be interested in I don't mind submitting a PR.

**Comment by aaiezza** [comment]
This is genius! I love it!

**Comment by jlorenzen** [comment]
@mchmielarz Thoughts?
