### ISSUE TITLE
Please release to Maven Central

### ISSUE THREAD

**Issue by qualidafial** [assertj/assertj-vavr#8]
`assertj-core` is in central, but not `assertj-vavr`. Please consider releasing to Maven Central so we can use this library more easily.

**Comment by pivovarit** [comment]
@qualidafial of course, the library will be available in Central as soon as it's written and stable :)

**Comment by pivovarit** [comment]
A small update here - we're getting ready to publish it to Central, we just need to go through initial bureaucracy first.

**Comment by jlorenzen** [comment]
@mchmielarz @pivovarit I see version `0.0.1` is up on maven central. Congrats guys! You should consider changing the version to `0.0.2-SNAPSHOT` in the pom.xml file on `master`. Otherwise it might be possible to release another `0.0.1` artifact and that wouldn't be good.

**Comment by pivovarit** [comment]
@jlorenzen totally, the road was bumpy but since now we should be able to work with the standard "mvn release" flow that should take care of that, thanks!
